sudo: required
services: 
  - docker

before_install:
  - docker build -t nutzull/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nutzull/react-test npm test

after_success:
  - docker build -t nutzull/multi-client ./client
  - docker build -t nutzull/multi-nginx ./nginx
  - docker build -t nutzull/multi-server ./server
  - docker build -t nutzull/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docker hub
  - docker push nutzull/multi-client 
  - docker push nutzull/multi-nginx
  - docker push nutzull/multi-server
  - docker push nutzull/multi-worker
